# CMake generated Testfile for 
# Source directory: /home/osboxes/Documents/code/CppUTest/tests/CppUTest
# Build directory: /home/osboxes/Documents/code/CppUTest/tests/CppUTest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(CppUTestTests.TeamCityOutputTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TeamCityOutputTest" "-c")
ADD_TEST(CppUTestTests.UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "UTestPlatformsTest_PlatformSpecificRunTestInASeperateProcess" "-c")
ADD_TEST(CppUTestTests.SimpleMutexTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "SimpleMutexTest" "-c")
ADD_TEST(CppUTestTests.CanHaveMemberVariablesInTestGroupThatAllocateMemoryWithoutCausingMemoryLeaks "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "CanHaveMemberVariablesInTestGroupThatAllocateMemoryWithoutCausingMemoryLeaks" "-c")
ADD_TEST(CppUTestTests.UtestMyOwn "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "UtestMyOwn" "-c")
ADD_TEST(CppUTestTests.IgnoredUtestShell "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "IgnoredUtestShell" "-c")
ADD_TEST(CppUTestTests.UtestShell "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "UtestShell" "-c")
ADD_TEST(CppUTestTests.UnitTestStringMacros "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "UnitTestStringMacros" "-c")
ADD_TEST(CppUTestTests.UnitTestMacros "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "UnitTestMacros" "-c")
ADD_TEST(CppUTestTests.TestResult "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestResult" "-c")
ADD_TEST(CppUTestTests.PluginTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "PluginTest" "-c")
ADD_TEST(CppUTestTests.TestRegistry "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestRegistry" "-c")
ADD_TEST(CppUTestTests.AllocLetTestFree "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "AllocLetTestFree" "-c")
ADD_TEST(CppUTestTests.CompositeTestOutput "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "CompositeTestOutput" "-c")
ADD_TEST(CppUTestTests.TestOutput "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestOutput" "-c")
ADD_TEST(CppUTestTests.MemoryLeakWarningThreadSafe "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakWarningThreadSafe" "-c")
ADD_TEST(CppUTestTests.MemoryLeakWarningGlobalDetectorTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakWarningGlobalDetectorTest" "-c")
ADD_TEST(CppUTestTests.MemoryLeakWarningTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakWarningTest" "-c")
ADD_TEST(CppUTestTests.MemoryLeakWarningLocalDetectorTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakWarningLocalDetectorTest" "-c")
ADD_TEST(CppUTestTests.FailableMemoryAllocator "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "FailableMemoryAllocator" "-c")
ADD_TEST(CppUTestTests.TestMemoryAllocatorTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestMemoryAllocatorTest" "-c")
ADD_TEST(CppUTestTests.OutOfMemoryTestsForOperatorNew "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "OutOfMemoryTestsForOperatorNew" "-c")
ADD_TEST(CppUTestTests.TestForExceptionsInConstructor "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestForExceptionsInConstructor" "-c")
ADD_TEST(CppUTestTests.MemoryLeakOverridesToBeUsedInProductionCode "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakOverridesToBeUsedInProductionCode" "-c")
ADD_TEST(CppUTestTests.BasicBehavior "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "BasicBehavior" "-c")
ADD_TEST(CppUTestTests.TestInstaller "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestInstaller" "-c")
ADD_TEST(CppUTestTests.ReallocBugReported "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "ReallocBugReported" "-c")
ADD_TEST(CppUTestTests.SimpleStringBuffer "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "SimpleStringBuffer" "-c")
ADD_TEST(CppUTestTests.MemoryLeakDetectorListTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakDetectorListTest" "-c")
ADD_TEST(CppUTestTests.MemoryLeakDetectorTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "MemoryLeakDetectorTest" "-c")
ADD_TEST(CppUTestTests.JUnitOutputTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "JUnitOutputTest" "-c")
ADD_TEST(CppUTestTests.TestHarness_c "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestHarness_c" "-c")
ADD_TEST(CppUTestTests.TestGroupInC "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestGroupInC" "-c")
ADD_TEST(CppUTestTests.TestFilter "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestFilter" "-c")
ADD_TEST(CppUTestTests.RunIgnoredTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "RunIgnoredTest" "-c")
ADD_TEST(CppUTestTests.CommandLineTestRunner "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "CommandLineTestRunner" "-c")
ADD_TEST(CppUTestTests.TestFailureNanAndInf "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestFailureNanAndInf" "-c")
ADD_TEST(CppUTestTests.TestFailure "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "TestFailure" "-c")
ADD_TEST(CppUTestTests.CommandLineArguments "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "CommandLineArguments" "-c")
ADD_TEST(CppUTestTests.SimpleString "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "SimpleString" "-c")
ADD_TEST(CppUTestTests.CheatSheet "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "CheatSheet" "-c")
ADD_TEST(CppUTestTests.SetPointerPluginTest "/home/osboxes/Documents/code/CppUTest/tests/CppUTest/CppUTestTests" "-sg" "SetPointerPluginTest" "-c")
